- name: Configure Elastic Search
  hosts: es
  remote_user: santatra
  become: true
  tasks:

    - name: Copy configuration files
      copy:
        src: conf/elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: root
        group: elasticsearch
        mode: '0660'

    - name: Ensure the ElasticSearch service is running
      service:
        name: elasticsearch
        state: restarted
