- name: Configure filebeat
  hosts: guest
  remote_user: santatra
  become: true
  tags: [ "filebeat" ]
  tasks:

    - name: Ensure the filebeat is running
      service:
        name: filebeat
        state: started

    - name: Copy configuration files
      copy:
        src: conf/filebeat.yml
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: '0660'

- name: Configure kibana
  hosts: guest
  remote_user: santatra
  become: true
  tags: [ "kibana" ]
  tasks:

    - name: Ensure the kibana is running
      service:
        name: kibana
        state: started

    - name: Copy configuration files
      copy:
        src: conf/kibana.yml
        dest: /etc/kibana/kibana.yml
        owner: root
        group: kibana
        mode: '0660'
