- name: Configure kibana
  hosts: dashboard
  remote_user: santatra
  become: true
  tasks:

    - name: Copy configuration files
      copy:
        src: conf/kibana.yml
        dest: /etc/kibana/kibana.yml
        owner: root
        group: kibana
        mode: '0660'

    - name: Ensure the kibana is running
      service:
        name: kibana
        state: started
